# Generated by Django 4.1.7 on 2023-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_priceperiod_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
