# Generated by Django 4.1.7 on 2023-03-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        ('properties', '0006_reservation_owner_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='owner',
        ),
        migrations.AddField(
            model_name='reservation',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_reservation', to='users.user'),
        ),
    ]
