# Generated by Django 4.1.7 on 2023-03-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_reservation_owner_reservation_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='reservation_date_end',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date_start',
            field=models.DateTimeField(default=datetime.date(2023, 3, 16)),
            preserve_default=False,
        ),
    ]
