# Generated by Django 4.1.7 on 2023-03-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_reservation_date_reservation_reservation_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date_start',
            new_name='date_start',
        ),
    ]
