# Generated by Django 4.1.7 on 2023-03-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
    ]
