# Generated by Django 4.1.7 on 2023-03-17 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_imagemodel_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reply_by',
            field=models.DateTimeField(default=datetime.date(2023, 3, 17)),
            preserve_default=False,
        ),
    ]
