# Generated by Django 4.1.7 on 2023-03-17 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_reservation_reply_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='properties.property'),
        ),
    ]
