# Generated by Django 4.1.7 on 2023-03-17 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereview',
            name='reviewer_name',
            field=models.CharField(default='Placeholder', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(default='Placeholder', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
